### ISSUE TITLE
Error when running the program

### ISSUE THREAD

**Issue by ferrygun** [juandes/PokemonTypesDeepLearning#2]
I am using tensorflow 0.11 to run your code, but I got the below error, any idea what's wrong? I guess is the compatibility issue, but I cannot figure it out how to resolve.

`Traceback (most recent call last):
  File "main.py", line 153, in <module>
    main()
  File "main.py", line 136, in main
    classifier.fit(reshaped_dataset, training_labels, logdir=os.getcwd() + 'model_20000b_logs')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 257, in fit
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 662, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 963, in _get_train_ops
    _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 946, in _call_model_fn
    return self._model_fn(features, targets, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 493, in _model_fn
    predictions, loss = model_fn(features, targets)
  File "main.py", line 93, in conv_model
    h_fc1 = learn.ops.dnn(
AttributeError: 'module' object has no attribute 'dnn'
`

**Comment by juandes** [comment]
Hi Ferry, I did the experiment using TensorFlow 0.10, and as far as I know the module `learn.ops.dnn` is deprecated and is not longer available in the recent releases. This is the TensorFlow commit where the change was done:
[Remove deprecated learn.ops](https://github.com/tensorflow/tensorflow/pull/4373/files)

Sorry for the inconvenience.

**Comment by ferrygun** [comment]
Thanks for your feedback Juan. I am downgrading to 0.10 now and will try again. Do let me know if you are able to run it in 0.11.
